package pianOvice;

import java.util.List;

public class Sample {
    public static final List<Note> track1Sample = List.of(
        new Note("A3", 57), 
        new Note("A3", 57), 
        new Note("𝄽", -48),
        new Note("A3", 57),
        new Note("E4", 64),
        new Note("E4", 64),
        new Note("A3", 57),
        new Note("E4", 64),
        new Note("F4", 65),
        new Note("F4", 65),
        new Note("G4", 67),
        new Note("F4", 65),
        new Note("C4", 60),
        new Note("C4", 60),
        new Note("𝄽", -48),
        new Note("𝄽", -48),
        new Note("D4", 62),
        new Note("D4", 62),
        new Note("𝄽", -48),
        new Note("D4", 62),
        new Note("C4", 60),
        new Note("C4", 60),
        new Note("A3", 57),
        new Note("C4", 60),
        new Note("D4", 62),
        new Note("D4", 62),
        new Note("G3", 55),
        new Note("G3", 55),
        new Note("E4", 64),
        new Note("E4", 64),
        new Note("𝄽", -48),
        new Note("𝄽", -48),
        new Note("A3", 57),
        new Note("A3", 57),
        new Note("𝄽", -48),
        new Note("A3", 57),
        new Note("E4", 64),
        new Note("E4", 64),
        new Note("𝄽", -48),
        new Note("E4", 64),
        new Note("F4", 65),
        new Note("F4", 65),
        new Note("G4", 67), 
        new Note("F4", 65),
        new Note("E4", 64),
        new Note("E4", 64),
        new Note("𝄽", -48),
        new Note("𝄽", -48),
        new Note("D4", 62),
        new Note("𝄽", -48),
        new Note("D4", 62),
        new Note("𝄽", -48),
        new Note("E4", 64),
        new Note("𝄽", -48),
        new Note("A3", 57),
        new Note("𝄽", -48),
        new Note("G3", 55),
        new Note("G3", 55),
        new Note("F#3", 54), 
        new Note("F#3", 54),
        new Note("E3", 52),
        new Note("E3", 52));

    public static final List<Note> track2Sample = List.of(
        new Note("E3", 52), new Note("E3", 52),
        new Note("𝄽", -48), new Note("𝄽", -48),
        new Note("B3", 59), new Note("B3", 59),
        new Note("𝄽", -48), new Note("𝄽", -48),
        new Note("C4", 60), new Note("C4", 60),
        new Note("𝄽", -48), new Note("𝄽", -48),
        new Note("G3", 55), new Note("G3", 55),
        new Note("𝄽", -48), new Note("𝄽", -48),
        new Note("A3", 57), new Note("A3", 57),
        new Note("𝄽", -48), new Note("𝄽", -48),
        new Note("G3", 55), new Note("G3", 55),
        new Note("𝄽", -48), new Note("𝄽", -48),
        new Note("A3", 57), new Note("A3", 57),
        new Note("𝄽", -48), new Note("𝄽", -48),
        new Note("B3", 59), new Note("B3", 59),
        new Note("𝄽", -48), new Note("𝄽", -48),
        new Note("E3", 52), new Note("E3", 52),
        new Note("𝄽", -48), new Note("𝄽", -48),
        new Note("B3", 59), new Note("B3", 59),
        new Note("𝄽", -48), new Note("𝄽", -48),
        new Note("C4", 60), new Note("C4", 60),
        new Note("𝄽", -48), new Note("𝄽", -48),
        new Note("C4", 60), new Note("C4", 60),
        new Note("𝄽", -48), new Note("𝄽", -48),
        new Note("A3", 57), 
        new Note("𝄽", -48), 
        new Note("A3", 57), 
        new Note("𝄽", -48), 
        new Note("C4", 60), 
        new Note("𝄽", -48), 
        new Note("E3", 52), 
        new Note("𝄽", -48), 
        new Note("G4", 67), new Note("𝄽", -48),
        new Note("F#4", 66), new Note("𝄽", -48),
        new Note("E4", 64), new Note("𝄽", -48));
}
